blog/urls.py
from django.urls import path
from .views import BlogCreateView, BlogDeleteView, BlogEditView, BlogListView

app_name="blog"

urlpatterns = [
    path("", BlogListView.as_view(), name="home"),
    path("create/", BlogCreateView.as_view(), name="create"),
    path("edit/<int:id>", BlogEditView.as_view(), name="edit"),
    path("delete/<int:id>", BlogDeleteView.as_view(), name="delete")
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("home/", HomeView.as_view(), name="home"),
    path("blog/", include('blog.urls', namespace="blog"))
]

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    date = models.DateField()

    def __str__(self) -> str:
        return self.title

blog/forms.py
from dataclasses import fields
from django import forms
from blog.models import Post

class DateInput(forms.DateInput):
    input_type = "date"

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title", "content", "date")
    title = forms.CharField(max_length=255)
    content = forms.CharField(widget=forms.Textarea)
    date = forms.DateField(widget=DateInput)
        

blog/views.py
from django.shortcuts import redirect, render
from django.views.generic import View
from .forms import PostCreateForm
from .models import Post

# Create your views here.
class BlogListView(View):
    def get(self, request, *args, **kwargs):
        posts = Post.objects.all()
        context = {
            "posts":posts
        }
        return render(request, "blog_list.html", context)

class BlogCreateView(View):
    def get(self, request, *args, **kwargs):
        form = PostCreateForm()
        context = {
            "form":form
        }
        return render(request, "blog_create.html", context)

    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            form = PostCreateForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data.get("title")
                content = form.cleaned_data.get("content")
                date = form.cleaned_data.get("date")

                post, created = Post.objects.get_or_create(title=title, content=content, date=date)
                post.save()

                return redirect("blog:home")

class BlogEditView(View):
    def get(self, request, *args, **kwargs):
        post = Post.objects.get(id=kwargs["id"])
        context = {
            "post":post
        }
        return render(request, "blog_edit.html", context)

    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            form = PostCreateForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data.get("title")
                content = form.cleaned_data.get("content")
                date = form.cleaned_data.get("date")

                post = Post.objects.get(id=kwargs["id"])
                post.title=title
                post.content=content
                post.date=date
                post.save()

                return redirect("blog:home")

class BlogDeleteView(View):
    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            post = Post.objects.get(id=kwargs["id"])
            post.delete()

        return redirect("blog:home")

core/views.py
from django.views.generic import View
from django.shortcuts import render

class HomeView(View):
    def get(self, request, *args, **kwargs):
        context = {}
        return render(request, "home.html", context)

templates/blog_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create post</title>
</head>
<body>
    <h1>Crea un nuevo post</h1>
    <form action="" method="post">
        {% csrf_token %}
        <label for="">Title:</label>
        {{form.title}}
        <br>
        <br>
        <label for="">Content:</label>
        {{form.content}}
        <br>
        <br>
        <label for="">Date:</label>
        {{form.date}}
        <br>
        <br>
        <button type="submit">Crear post</button>
    </form>
</body>
</html>

templates/blog_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit post</title>
</head>
<body>
    <h1>Editando un post</h1>
    <form action="" method="post">
        {% csrf_token %}
        <label for="">Title</label>
        <input type="text" value="{{ post.title }}" name="title">
        <br>
        <br>
        
        <label for="">Title</label>
        <textarea name="content" id="" cols="30" rows="10">{{post.content}}</textarea>
        <br>
        <br>
        <label for="">Title</label>
        <input type="date" value="{{post.date|date:'Y-m-d'}}" name="date">
        <br>
        <br>
        <button type="submit">Guardar post</button>
        <a href="{% url 'blog:home' %}">Cancelar</a>
    </form>
    
</body>
</html>

templates/blog_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog Home</title>
</head>
<body>
    <h1>¡Bienvenido a mi Blog!</h1>
    {% if posts %}
        <p>Estos son algunos posts</p>
        {% for post in posts %}
            <label for=""><strong>Title:</strong></label>
            <span>{{ post.title }}</span>
            <br>
            <label for=""><strong>Content:</strong></label>
            <span>{{ post.content }}</span>
            <br>
            <label for=""><strong>Publication date:</strong></label>
            <span>{{ post.date }}</span>
            <br>
            <a href="{% url 'blog:edit' id=post.id %}">Editar</a>
            <form action="{% url 'blog:delete' id=post.id %}" method="post" id="myform">
                {% csrf_token %}
                <button type="submit" id="btn-del">Eliminar</button>
            </form>
            <br>
            <br>
        {% endfor %}
    {% else %}
        <p>No hay posts para mostrar</p>
    {% endif %}
    <p>Crea un nuevo post <a href="{% url 'blog:create' %}">aquí</a></p>

    

</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>Hola mundo</h1>
    <p>Visita mi blog <a href="{% url 'blog:home' %}">aquí</a></p>
</body>
</html>